apiVersion: v1
kind: Service
metadata:
  labels:
    app: cert-exporter
  name: cert-exporter
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cert-exporter
